version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kanban_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kanban_db
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
